name: coexpression
channels:
- defaults
dependencies:
- backports=1.0=py27_0
- cairo=1.14.8=0
- certifi=2016.2.28=py27_0
- cycler=0.10.0=py27_0
- dbus=1.10.20=0
- decorator=4.1.2=py27_0
- enum34=1.1.6=py27_0
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- functools32=3.2.3.2=py27_0
- get_terminal_size=1.0.0=py27_0
- glib=2.50.2=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- icu=54.1=0
- ipython=5.3.0=py27_0
- ipython_genutils=0.2.0=py27_0
- jpeg=9b=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.30=1
- libxcb=1.12=1
- libxml2=2.9.4=0
- matplotlib=2.0.2=np111py27_0
- memory_profiler=0.43=py27_0
- mkl=2017.0.3=0
- networkx=1.11=py27_0
- numpy=1.11.3=py27_0
- openssl=1.0.2l=0
- pandas=0.18.1=np111py27_0
- path.py=10.3.1=py27_0
- pathlib2=2.3.0=py27_0
- pcre=8.39=1
- pexpect=4.2.1=py27_0
- pickleshare=0.7.4=py27_0
- pip=9.0.1=py27_1
- pixman=0.34.0=0
- prompt_toolkit=1.0.15=py27_0
- psutil=5.2.2=py27_0
- ptyprocess=0.5.2=py27_0
- pycairo=1.10.0=py27_0
- pygments=2.2.0=py27_0
- pyparsing=2.2.0=py27_0
- pyqt=5.6.0=py27_2
- python=2.7.13=0
- python-dateutil=2.6.1=py27_0
- pytz=2017.2=py27_0
- qt=5.6.2=5
- readline=6.2=2
- scandir=1.5=py27_0
- scipy=0.19.0=np111py27_0
- setuptools=36.4.0=py27_1
- simplegeneric=0.8.1=py27_1
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- subprocess32=3.2.7=py27_0
- tk=8.5.18=0
- traitlets=4.3.2=py27_0
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.11=0
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.2.0
  - memory-profiler==0.43
  - prompt-toolkit==1.0.15
prefix: /exports/cmvm/eddie/eb/groups/baillielab2/conda_envs/coexpression

